from fastapi import FastAPI
from app.routers import user, transaction, team, agent, appointment, contact, lead_analytics, invite, phone_campaign, email_campaign, linkdin_post, scheduled_content, whatsapp_connection, account_chat_history, appointment_agent, Callrecord , content, googlecalender, auth #, instagram_connection, linkedin_connection, knowledge_base, password_reset, x_post, youtube_script

app = FastAPI(title="Super Admin API")

app.include_router(user.router, prefix="/super-admin")
app.include_router(transaction.router, prefix="/super-admin")
app.include_router(team.router, prefix="/super-admin")
app.include_router(agent.router, prefix="/super-admin") 
app.include_router(appointment.router, prefix="/super-admin")
app.include_router(contact.router, prefix="/super-admin")
app.include_router(lead_analytics.router, prefix="/super-admin")
app.include_router(invite.router, prefix="/super-admin")
app.include_router(phone_campaign.router, prefix="/super-admin")
app.include_router(email_campaign.router, prefix="/super-admin")
app.include_router(linkdin_post.router, prefix="/super-admin")
app.include_router(scheduled_content.router, prefix="/super-admin")
app.include_router(whatsapp_connection.router, prefix="/super-admin")
app.include_router(account_chat_history.router, prefix="/super-admin")
app.include_router(appointment_agent.router, prefix="/super-admin")
app.include_router(Callrecord.router, prefix="/super-admin")
app.include_router(content.router, prefix="/super-admin")
app.include_router(googlecalender.router, prefix="/super-admin")
app.include_router(auth.router)
# app.include_router(instagram_connection.router, prefix="/super-admin")
# app.include_router(linkedin_connection.router, prefix="/super-admin")
# app.include_router(knowledge_base.router, prefix="/super-admin")
# app.include_router(password_reset.router, prefix="/super-admin")
# app.include_router(x_post.router, prefix="/super-admin")
# app.include_router(youtube_script.router, prefix="/super-admin")